# Generated by Django 6.1 on 2026-09-06 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('COMPLETO', 'Completo'), ('EXPRESS', 'Express'), ('EXTERIORES', 'Exteriores')], default='COMPLETO', max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN PROCESO', 'En proceso'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='solicitudServicio.servicio')),
            ],
        ),
    ]
