# Generated by Django 6.1 on 2026-09-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('COMPLETA', 'Completa'), ('EXPRESS', 'Express'), ('EXTERIORES', 'Exteriores')], default='COMPLETA', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('OFICINA', 'Oficina')], default='PENDIENTE', max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN PROCESO', 'En proceso'), ('TERMINADO', 'Terminado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
