# Generated by Django 6.1 on 2026-09-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudServicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='servicio',
        ),
    ]
