# Generated by Django 6.1 on 2026-09-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudServicio', '0002_remove_servicio_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('OFICINA', 'Oficina')], default='CASA', max_length=15),
        ),
    ]
